//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketUygulama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cashiers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cashiers()
        {
            this.SalesLists = new HashSet<SalesLists>();
        }
    
        public int CashierId { get; set; }
        public string KasiyerAdi { get; set; }
        public string KasiyerSoyad { get; set; }
        public string TcKimlik { get; set; }
        public string CepTel { get; set; }
        public string Adres { get; set; }
        public string GorevlioldKasa { get; set; }
        public Nullable<System.DateTime> İseGirmeTarihi { get; set; }
        public Nullable<System.DateTime> İstenCikma { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesLists> SalesLists { get; set; }
    }
}
