//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketUygulama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.SalesLists = new HashSet<SalesLists>();
        }
    
        public int ProductId { get; set; }
        public int CategoryId { get; set; }
        public int CompanyId { get; set; }
        public string UrunAdi { get; set; }
        public string UrunKodu { get; set; }
        public string AlisFiyati { get; set; }
        public string SatisFiyati { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Companyes Companyes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesLists> SalesLists { get; set; }
        public virtual Stocks Stocks { get; set; }
    }
}
